spring:
  jpa:
    show-sql: false
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        query.substitutions: true 1, false 0
        default_batch_fetch_size: 50
        jdbc.batch_size: 50
        order_inserts: true
        max_fetch_depth: 2
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
        connection.zeroDateTimeBehavior: convertToNull

  mvc:
    throw-exception-if-no-handler-found: true

  resources:
    add-mappings: true

  cloud:
    stream:
      instanceCount: 1
      instanceIndex: 0
      rabbitmq:
        binder:
          adminAddresses: ${CONFIG_SERVER_IP:192.168.0.9}:15672

        bindings:
          input:
            consumer:
              autoCommitOffset: true
          output:
            producer:
              acknowledgeMode: 'AUTO'
  rabbitmq:
    addresses: ${CONFIG_SERVER_IP:192.168.0.9}:5672
    username: xintuo
    password: xintuo 

myapp:
  zkNodes: ${CONFIG_SERVER_IP:192.168.0.9}:2181
# Discovery Server Access
eureka:
  instance:
    # hostname: localhost
    preferIpAddress: true

  client:
    serviceUrl:
      defaultZone: http://${CONFIG_SERVER_IP:192.168.0.9}:1111/eureka/

hystrix:
  command.default.execution.isolation.thread.timeoutInMilliseconds: 3000
  threadpool.default.coreSize: 10

feign:
  hystrix:
    enabled: false
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048




