spring:
  application:
    name: shop-rule
    index: 0

  datasource:
    url: jdbc:mysql://${CONFIG_SERVER_IP:192.168.0.9}:3306/xt_shop_rule_service
    username: root
    password: xiey
    testWhileIdle: true
    validationQuery: SELECT 1

  cloud:
    stream:
      instanceCount: 1
      instanceIndex: 0
      bindings:
        input:
          # destination: testq1
          group: shop-rule
          consumer:
            concurrency: 1
            partitioned: false
            headerMode: raw
        output:
          # destination: testq2
          group: shop-rule
          producer:
            # partitionKeyExpression: null
            # partitionKeyExtractorClass: null
            # partitionSelectorExpression: null
            # partitionSelectorClass: null
            partitionCount: 1
            headerMode: raw





