spring:
  application:
    name: web-common-admin
    index: 0

  datasource:
    url: jdbc:mysql://${CONFIG_SERVER_IP:192.168.0.9}:3306/xt_web_common_admin
    username: root
    password: xiey
    testWhileIdle: true
    validationQuery: SELECT 1

  cloud:
    stream:
      instanceCount: 1
      instanceIndex: 0

      bindings:
        input:
          # destination: testq1
          group: web-common-admin
          consumer:
            concurrency: 1
            partitioned: false
            headerMode: raw
        output:
          # destination: testq2
          group: web-common-admin
          producer:
            # partitionKeyExpression: null
            # partitionKeyExtractorClass: null
            # partitionSelectorExpression: null
            # partitionSelectorClass: null
            partitionCount: 1
            headerMode: raw
  mvc:
    view:
      suffix: .html
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
